create table report
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table report_field
(
    id          bigint generated by default as identity,
    report      bigint,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table report_image
(
    id            bigint generated by default as identity,
    description   varchar(255),
    name          varchar(255),
    relative_path varchar(255),
    primary key (id)
);
create table report_image_linker
(
    image  bigint not null,
    report bigint not null,
    primary key (image, report)
);
create table report_locale
(
    id            bigint generated by default as identity,
    template_path varchar(255),
    content       varchar(255),
    primary key (id)
);
create table report_locale_linker
(
    locale bigint not null,
    report bigint not null,
    primary key (locale, report)
);
create table report_table_column
(
    id              bigint generated by default as identity,
    report_table_id bigint,
    description     varchar(255),
    name            varchar(255),
    primary key (id)
);
create table report_table
(
    id          bigint generated by default as identity,
    report      bigint,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);