name: Code Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies and run tests with JaCoCo
      run: mvn clean test jacoco:report

    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v3
      with:
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        output: README.md
        badge-template: "Coverage: {PERCENT}%"
    
    - name: Commit coverage badge
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update coverage badge in README"
      continue-on-error: true  # Allow no changes to continue

    - name: Push changes
      run: git push
      if: success()
