name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the Java distribution here

      - name: Build with Maven
        run: mvn clean install

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
            COVERAGE=$(grep -oP '(?<=<lineCoverage>)[0-9]+(?=%</lineCoverage>)' target/site/jacoco/jacoco.xml | head -n 1)
            echo "Coverage Percentage: $COVERAGE"
            echo "::set-output name=coverage::$COVERAGE"

      - name: Update README with Coverage Badge
        run: |
                COVERAGE=${{ steps.extract-coverage.outputs.coverage }}
                echo "Updating README with coverage badge..."
                BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-green"
                sed -i "s|https://img.shields.io/badge/coverage-.*-green|$BADGE_URL|g" README.md
                git config --local user.name "github-actions"
                git config --local user.email "github-actions@github.com"
                git commit -am "Update coverage badge to $COVERAGE%"
                git push

      - name: Commit updated README
        if: steps.extract-coverage.outputs.coverage != ''
        run: |
                git add README.md
                git commit -m "Update coverage badge"
                git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}