name: Code Coverage

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Change this to your JDK version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean test

      - name: Generate Coverage Badge
        run: |
          # Path to your JaCoCo XML report
          report="target/site/jacoco/jacoco.xml"  # For Maven
          
          # Extract coverage percentage from JaCoCo report
          coverage=$(grep -oP '(?<=linecoverage=")[0-9]+(\.[0-9]+)?' "$report")
          
          # Create a badge Markdown text
          badge="[![Coverage](https://img.shields.io/badge/coverage-${coverage}%25-brightgreen.svg)](https://github.com/zatribune/springboot-jasperreports-advanced-demo)"
          
          # Write the badge to a markdown file
          echo "$badge" > coverage-badge.md

      - name: Commit and push changes
        run: |
          git config --local user.email "you@example.com"  # Change to your email
          git config --local user.name "Your Name"  # Change to your name
          git add coverage-badge.md
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push origin main  # Change to your default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}